export const TILE_SIZE = 32;

export const terrainTiles = {
  grass: { color: 0x73c65d, walkable: true },
  flowerGrass: { color: 0x6fc45a, walkable: true },
  dirtPath: { color: 0xc58d4f, walkable: true },
  water: { color: 0x3598d4, walkable: false },
  woodFloor: { color: 0xc98b50, walkable: true },
  lightRedFloor: { color: 0xf3b6ac, walkable: true },
  lightGreenFloor: { color: 0xbce7b3, walkable: true },
  insideWall: { color: 0x8d6b57, walkable: false },
  stoneFloor: { color: 0xb7b7ad, walkable: true },
  asphalt: { color: 0x56616b, walkable: true },
  track: { color: 0xb64c2e, walkable: true },
  gymFloor: { color: 0xd6a348, walkable: true },
  carpetBlue: { color: 0x4568a8, walkable: true },
  campusStone: { color: 0xd6d2c4, walkable: true }
};

export const objectTypes = {
  tree: { color: 0x2f8f3b, walkable: false, label: "Tree" },
  fence: { color: 0x9a6733, walkable: false, label: "Fence" },
  stoneWall: { color: 0x777f86, walkable: false, label: "Stone wall" },
  water: { color: 0x3598d4, walkable: false, label: "Water" },
  houseBlue: { color: 0x4f8fd8, walkable: false, label: "Blue house" },
  houseRed: { color: 0xd95448, walkable: false, label: "Red house" },
  houseGreen: { color: 0x50a96b, walkable: false, label: "Green house" },
  restaurant: { color: 0xf28c38, walkable: false, label: "Restaurant" },
  store: { color: 0xb46adf, walkable: false, label: "Store" },
  school: { color: 0xf0c84b, walkable: false, label: "School" },
  office: { color: 0x7d8aa2, walkable: false, label: "Office" },
  gym: { color: 0xe67e22, walkable: false, label: "Gym" },
  library: { color: 0x4f8fd8, walkable: false, label: "Library" },
  dorm: { color: 0x50a96b, walkable: false, label: "Dorm" },
  auditorium: { color: 0x9b59b6, walkable: false, label: "Auditorium" },
  table: { color: 0x8d5524, walkable: false, label: "Table" },
  bench: { color: 0x8d5524, walkable: false, label: "Bench" },
  desk: { color: 0x7b4f2d, walkable: false, label: "Desk" },
  computerDesk: { color: 0x7b4f2d, walkable: false, label: "Computer desk" },
  studyDesk: { color: 0x7b4f2d, walkable: false, label: "Study desk" },
  teacherDesk: { color: 0x7b4f2d, walkable: false, label: "Teacher desk" },
  chair: { color: 0x61432a, walkable: false, label: "Chair" },
  counter: { color: 0xd7d0b1, walkable: false, label: "Counter" },
  serviceCounter: { color: 0xd7d0b1, walkable: false, label: "Service counter" },
  hotelDesk: { color: 0xd7d0b1, walkable: false, label: "Hotel desk" },
  mailCounter: { color: 0xd7d0b1, walkable: false, label: "Mail counter" },
  couch: { color: 0x6b8fd6, walkable: false, label: "Couch" },
  bed: { color: 0xefefdc, walkable: false, label: "Bed" },
  dormBed: { color: 0xefefdc, walkable: false, label: "Dorm bed" },
  doctorBed: { color: 0xefefdc, walkable: false, label: "Doctor bed" },
  crib: { color: 0xefefdc, walkable: false, label: "Crib" },
  plant: { color: 0x36a853, walkable: false, label: "Plant" },
  shelf: { color: 0x9c6a3d, walkable: false, label: "Shelf" },
  bookshelf: { color: 0x9c6a3d, walkable: false, label: "Bookshelf" },
  groceryShelf: { color: 0x9c6a3d, walkable: false, label: "Grocery shelf" },
  supplyShelf: { color: 0x9c6a3d, walkable: false, label: "Supply shelf" },
  sign: { color: 0xf5df8f, walkable: false, label: "Sign" },
  chalkboard: { color: 0x2f6f4f, walkable: false, label: "Chalkboard" },
  whiteboard: { color: 0xf5f7fa, walkable: false, label: "Whiteboard" },
  bulletinBoard: { color: 0xb98245, walkable: false, label: "Bulletin board" },
  clubBooth: { color: 0xffd166, walkable: false, label: "Club booth" },
  locker: { color: 0x5b7ca8, walkable: false, label: "Locker" },
  cubby: { color: 0xc98b50, walkable: false, label: "Cubby" },
  crayonBox: { color: 0xffd166, walkable: false, label: "Crayon box" },
  lunchTray: { color: 0xd7d0b1, walkable: false, label: "Lunch tray" },
  slide: { color: 0xff6b6b, walkable: false, label: "Slide" },
  swings: { color: 0x8d5524, walkable: false, label: "Swings" },
  sportsGoal: { color: 0xffffff, walkable: false, label: "Sports goal" },
  gymMat: { color: 0x2f66d0, walkable: true, label: "Gym mat" },
  podium: { color: 0x8d5524, walkable: false, label: "Podium" },
  printer: { color: 0xd5dbe7, walkable: false, label: "Printer" },
  meetingTable: { color: 0x8d5524, walkable: false, label: "Meeting table" },
  interviewChair: { color: 0x61432a, walkable: false, label: "Interview chair" },
  kitchenCounter: { color: 0xd7d0b1, walkable: false, label: "Kitchen counter" },
  fridge: { color: 0xd9f2ff, walkable: false, label: "Fridge" },
  stove: { color: 0x5d6673, walkable: false, label: "Stove" },
  atm: { color: 0x2f66d0, walkable: false, label: "ATM" },
  busStop: { color: 0x7d8aa2, walkable: false, label: "Bus stop" },
  luggage: { color: 0x8d5524, walkable: false, label: "Luggage" },
  ticketKiosk: { color: 0x7d8aa2, walkable: false, label: "Ticket kiosk" },
  airportGate: { color: 0x90c9f6, walkable: false, label: "Airport gate" },
  taxiStand: { color: 0xffd166, walkable: false, label: "Taxi stand" },
  menuBoard: { color: 0x2f6f4f, walkable: false, label: "Menu board" },
  birthdayTable: { color: 0xff86b7, walkable: false, label: "Birthday table" },
  familyPhoto: { color: 0xf5df8f, walkable: false, label: "Family photo" },
  toyBox: { color: 0xffd166, walkable: false, label: "Toy box" },
  grill: { color: 0x5d6673, walkable: false, label: "Grill" },
  filingCabinet: { color: 0x7d8aa2, walkable: false, label: "Filing cabinet" },
  formDesk: { color: 0x7b4f2d, walkable: false, label: "Form desk" },
  taxFormDesk: { color: 0x7b4f2d, walkable: false, label: "Tax form desk" },
  queueRope: { color: 0xb64c2e, walkable: false, label: "Queue rope" },
  car: { color: 0xe74c3c, walkable: false, label: "Car" },
  toolBench: { color: 0x8d5524, walkable: false, label: "Tool bench" },
  ballotBox: { color: 0xf5f7fa, walkable: false, label: "Ballot box" },
  microphone: { color: 0x111827, walkable: false, label: "Microphone" },
  eventBooth: { color: 0xffd166, walkable: false, label: "Event booth" },
  townBoard: { color: 0xb98245, walkable: false, label: "Town board" },
  trophyCase: { color: 0xf5df8f, walkable: false, label: "Trophy case" },
  labTable: { color: 0xd5dbe7, walkable: false, label: "Lab table" },
  labSink: { color: 0x90c9f6, walkable: false, label: "Lab sink" },
  vendingMachine: { color: 0xe74c3c, walkable: false, label: "Vending machine" },
  schoolBell: { color: 0xffd166, walkable: false, label: "School bell" },
  campusFountain: { color: 0x3598d4, walkable: false, label: "Campus fountain" },
  bikeRack: { color: 0x7d8aa2, walkable: false, label: "Bike rack" },
  laundryMachine: { color: 0xd9f2ff, walkable: false, label: "Laundry machine" },
  coffeeMachine: { color: 0x8d5524, walkable: false, label: "Coffee machine" },
  examDesk: { color: 0x7b4f2d, walkable: false, label: "Exam desk" },
  suitcase: { color: 0x8d5524, walkable: false, label: "Suitcase" },
  passportDesk: { color: 0x7b4f2d, walkable: false, label: "Passport desk" },
  dreamBoard: { color: 0x7d8aa2, walkable: false, label: "Dream board" },
  skyline: { color: 0x34495e, walkable: false, label: "Skyline" },
  questSparkle: { color: 0xffd166, walkable: true, label: "Quest sparkle" },
  itemSparkle: { color: 0x8ed8ff, walkable: true, label: "Item sparkle" },
  routeGate: { color: 0xffd166, walkable: false, label: "Route gate" }
};

export const people = [
  { id: "ana", name: "Ana", color: 0xe74c3c, hair: 0x3b2416, skin: 0xf0ad7a, outfit: "dress", accent: 0xffd166 },
  { id: "mateo", name: "Mateo", color: 0x3498db, hair: 0x1f2937, skin: 0xc98255, outfit: "jacket", accent: 0xffffff },
  { id: "sofia", name: "Sofia", color: 0x9b59b6, hair: 0x5b3518, skin: 0xe4a06f, outfit: "teacher", accent: 0xfff2bf },
  { id: "carlos", name: "Carlos", color: 0x2ecc71, hair: 0x252018, skin: 0xb8754e, outfit: "apron", accent: 0xf5df8f },
  { id: "lucia", name: "Lucia", color: 0xf1c40f, hair: 0x6d421f, skin: 0xf2b37e, outfit: "dress", accent: 0xff86b7 },
  { id: "diego", name: "Diego", color: 0xe67e22, hair: 0x2b180f, skin: 0xd9905f, outfit: "vest", accent: 0x8ed8ff },
  { id: "isabel", name: "Isabel", color: 0x1abc9c, hair: 0x2f1b12, skin: 0xbc7a55, outfit: "dress", accent: 0xffffff },
  { id: "nico", name: "Nico", color: 0x34495e, hair: 0x111827, skin: 0xd9905f, outfit: "hoodie", accent: 0xffd166 },
  { id: "emma", name: "Emma", color: 0xff79b0, hair: 0x7b4f2d, skin: 0xf2b37e, outfit: "apron", accent: 0xffffff },
  { id: "tomás", name: "Tomas", color: 0x95a5a6, hair: 0xd9d2c3, skin: 0xc98255, outfit: "jacket", accent: 0x2f66d0 }
  ,
  { id: "valeria", name: "Valeria", color: 0x6c5ce7, hair: 0x2f1b12, skin: 0xe4a06f, outfit: "jacket", accent: 0xffd166 },
  { id: "marcos", name: "Marcos", color: 0x00a8a8, hair: 0x1f2937, skin: 0xb8754e, outfit: "hoodie", accent: 0xffffff },
  { id: "elena", name: "Elena", color: 0xff6b6b, hair: 0x5b3518, skin: 0xf2b37e, outfit: "teacher", accent: 0xffffff },
  { id: "javier", name: "Javier", color: 0x2d3436, hair: 0x111827, skin: 0xd9905f, outfit: "vest", accent: 0xffd166 },
  { id: "guardian-aula", name: "Guardiana del Aula", color: 0x7c3aed, hair: 0x111827, skin: 0xf2b37e, outfit: "teacher", accent: 0xffd166 },
  { id: "guardian-patio", name: "Guardián del Patio", color: 0x0f766e, hair: 0x2b180f, skin: 0xd9905f, outfit: "vest", accent: 0x8ed8ff },
  { id: "guardian-biblioteca", name: "Guardiana de la Biblioteca", color: 0xbe123c, hair: 0x5b3518, skin: 0xe4a06f, outfit: "dress", accent: 0xffffff },
  { id: "mentor-horario", name: "Mentor del Horario", color: 0x2563eb, hair: 0x111827, skin: 0xc98255, outfit: "jacket", accent: 0xffd166 },
  { id: "capitana-equipo", name: "Capitana del Equipo", color: 0xdc2626, hair: 0x3b2416, skin: 0xf0ad7a, outfit: "vest", accent: 0xffffff },
  { id: "directora-club", name: "Directora del Club", color: 0x9333ea, hair: 0x2f1b12, skin: 0xe4a06f, outfit: "teacher", accent: 0xf5df8f },
  { id: "mentor-dormitorio", name: "Mentor del Dormitorio", color: 0x16a34a, hair: 0x111827, skin: 0xd9905f, outfit: "hoodie", accent: 0xffffff },
  { id: "profesora-biblioteca", name: "Profesora de Biblioteca", color: 0x0891b2, hair: 0x5b3518, skin: 0xf2b37e, outfit: "teacher", accent: 0xffd166 },
  { id: "rectora-campus", name: "Rectora del Campus", color: 0x4f46e5, hair: 0x2f1b12, skin: 0xe4a06f, outfit: "jacket", accent: 0xffffff }
];

export const items = {
  coins: { id: "coins", name: "coins", spanish: "monedas" },
  milk: { id: "milk", name: "milk", spanish: "leche" },
  rosaLetter: { id: "rosaLetter", name: "Rosa's letter", spanish: "carta de Rosa" },
  routePass: { id: "routePass", name: "route pass", spanish: "pase del camino" },
  greetingBadge: { id: "greetingBadge", name: "greeting badge", spanish: "insignia de saludo" },
  nameCard: { id: "nameCard", name: "name card", spanish: "tarjeta de nombre" },
  waterBottle: { id: "waterBottle", name: "water bottle", spanish: "botella de agua" },
  bread: { id: "bread", name: "bread", spanish: "pan" },
  apple: { id: "apple", name: "apple", spanish: "manzana" },
  marketStamp: { id: "marketStamp", name: "market stamp", spanish: "sello del mercado" },
  notebook: { id: "notebook", name: "notebook", spanish: "cuaderno" },
  pencil: { id: "pencil", name: "pencil", spanish: "lápiz" },
  studyStar: { id: "studyStar", name: "study star", spanish: "estrella de estudio" },
  morningStar: { id: "morningStar", name: "morning star", spanish: "estrella de la mañana" },
  nameTag: { id: "nameTag", name: "name tag", spanish: "etiqueta de nombre" },
  politePass: { id: "politePass", name: "polite pass", spanish: "pase amable" },
  schoolMap: { id: "schoolMap", name: "school map", spanish: "mapa de la escuela" },
  bluePencil: { id: "bluePencil", name: "blue pencil", spanish: "lápiz azul" },
  redBook: { id: "redBook", name: "red book", spanish: "libro rojo" },
  greenNotebook: { id: "greenNotebook", name: "green notebook", spanish: "cuaderno verde" },
  eraser: { id: "eraser", name: "eraser", spanish: "borrador" },
  playgroundBall: { id: "playgroundBall", name: "ball", spanish: "pelota" },
  lostToy: { id: "lostToy", name: "lost toy", spanish: "juguete perdido" },
  lunchTrayItem: { id: "lunchTrayItem", name: "lunch tray", spanish: "bandeja" },
  juiceBox: { id: "juiceBox", name: "juice box", spanish: "jugo" },
  libraryCard: { id: "libraryCard", name: "library card", spanish: "tarjeta de biblioteca" },
  artPoster: { id: "artPoster", name: "art poster", spanish: "cartel de arte" },
  chapterOneBadge: { id: "chapterOneBadge", name: "chapter one badge", spanish: "insignia del capítulo uno", category: "badge" },
  scheduleCard: { id: "scheduleCard", name: "schedule card", spanish: "horario" },
  clubForm: { id: "clubForm", name: "club form", spanish: "formulario del club" },
  gymPass: { id: "gymPass", name: "gym pass", spanish: "pase del gimnasio" },
  scienceKit: { id: "scienceKit", name: "science kit", spanish: "kit de ciencias" },
  cafeteriaTicket: { id: "cafeteriaTicket", name: "cafeteria ticket", spanish: "boleto de cafetería" },
  chapterTwoBadge: { id: "chapterTwoBadge", name: "chapter two badge", spanish: "insignia del capítulo dos", category: "badge" },
  dormKey: { id: "dormKey", name: "dorm key", spanish: "llave del dormitorio" },
  textbook: { id: "textbook", name: "textbook", spanish: "libro de texto" },
  calculator: { id: "calculator", name: "calculator", spanish: "calculadora" },
  coffeeCup: { id: "coffeeCup", name: "coffee", spanish: "café" },
  campusId: { id: "campusId", name: "campus ID", spanish: "identificación universitaria" },
  studyNotes: { id: "studyNotes", name: "study notes", spanish: "apuntes" },
  chapterThreeBadge: { id: "chapterThreeBadge", name: "chapter three badge", spanish: "insignia del capítulo tres", category: "badge" }
};

export function getObjectType(type) {
  return objectTypes[type] || objectTypes.tree;
}
